### PR TITLE
Add image support for iOS and some convenience helpers for iOS relate…

### PR DESCRIPTION
**Pull request by mphill**
### What does this PR do?
This will add image attachments for iOS.

There are also some helper methods added to the iOS NotificationCenter class.  Android does not have this capability to it was isolated to NotificationCenter.

They allow you to see what notifications are schedules and also what has been delivered.

##### Why are we doing this? Any context or related work?
https://github.com/thudugala/Plugin.LocalNotification/issues/130

### CODE REVIEW

**Review by thudugala — CHANGES_REQUESTED** [review]
without using iOSNotification, can we use NotificationRequest ?

**Comment by mphill** [comment]
iOSNotification is a light weight wrapper to represent Pending and Delivered notifications on iOS.  Unfortunately iOS doesn't give us enough information to recreate the whole NotificationRequest.

I looked into the Android side a little bit more too, I think we can get pending notifications like this:

```
var workQuery = WorkQuery.Builder.FromStates(new List<WorkInfo.State>() { WorkInfo.State.Enqueued }).Build();

var pending = WorkManager?.GetWorkInfos(workQuery); 
```


We could just make the return type of Pending /Delivered notifications IEnumerable<int>

**Comment by thudugala** [comment]
@mphill 

have you looked at LocalNotificationDelegate.GetRequest, it may help

**Comment by mphill** [comment]
I removed the iOSNoticication class.  Thanks for the help!

**Comment by thudugala** [comment]
@mphill Can we support images that are not project it self, Can we show a image that we get from a web api call ?

**Comment by mphill** [comment]
I don’t think URLs work with attachments, the file must first be downloaded. Is this what you intended? 

I can work on support for images in Xamarin.Forms shared projects.

**Comment by mphill** [comment]
If you use an embedded resource for the image it will require the file be extracted from the binary and copied to a local folder. I think it's better to keep these in the native Resources folders.

**Review by thudugala — APPROVED** [review]

**Pull request merged**
