### PR TITLE
Fix #112

### LINKED ISSUE #112: [BUG] When negating permission the first time on iOS, the app needs to be killed to read new permission gave from the ios settings
If i negate notification permissions the first time the `NotificationPlugin` asks for them, and then i go to the iOS settings (while my app is still in background) and allow the notification, the `NotificationPlugin` dont "see" the new permission unless the app is killed and reopened

I think this is due the `static bool _alertsAllowed` always return its value when already sets.
so when we change the permissions while the app is still in memory, the new check will never happen until the app is killed.

I tried this on iOS only, maybe there is the same issue in Android.

i see two options:
- the plugin needs to always check it's permission (at least when the "allow" is "false"

- let us to check and request permission directly in shared code

### PR DESCRIPTION
**Pull request by GiampaoloGabba**
Ensure to always check permissions on iOS

### CODE REVIEW

**Comment by thudugala** [comment]
@GiampaoloGabba If a user say no to notification. Wouldn't this correction keep asking for it ? even user said no.

**Comment by GiampaoloGabba** [comment]
Nope, iOS shows the permission popup only the first time you request it. Every other request are handled silently (even of you kill the app).

So when you negate it the first time, every subsequent request always return false without any request popup.

After the request is negated you can enable it only from the iOS settings.

________________________________
Da: Elvin (Tharindu) Thudugala <notifications@github.com>
Inviato: Thursday, September 24, 2020 10:51:45 PM
A: thudugala/Plugin.LocalNotification <Plugin.LocalNotification@noreply.github.com>
Cc: Giampaolo Gabba <info@evolutionlab.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [thudugala/Plugin.LocalNotification] Fix #112 (#113)


@GiampaoloGabba<https://github.com/GiampaoloGabba> If a user say no to notification. Wouldn't this correction keep asking for it ? even user said no.

**Comment by thudugala** [comment]
@GiampaoloGabba so then no point having _alertsAllowed,  can you please also remove the variable

**Comment by GiampaoloGabba** [comment]
Shure!

**Review by thudugala — CHANGES_REQUESTED** [review]
Please remove static variable _alertsAllowed

**Comment by GiampaoloGabba** [comment]
done

**Review by thudugala — APPROVED** [review]

**Pull request merged**
